### PR TITLE
Store camera position between reloads

### PR DESCRIPTION
**Pull request by danhigham**
Hello Dan!

This is persisting the camera position in it's most simple form. I could probably add functionality to clear it in the clean up routine. Or is it best left?!

### CODE REVIEW

**Comment by danmarshall** [comment]
Thanks!! It's been a while, but IIRC the cleanup routine is only on the server side anyways.
Perhaps the only issue I could see is if one got themselves into a faraway camera position (like a large model) and then quit, and then started working on a tiny model, which could be invisible from that leftover faraway camera position.
Maye we can add a "reset camera" button?

**Comment by danhigham** [comment]
Sounds good to me! I'm not familiar with nanohtml, can you point me towards any handy guides on the view / controller type setup you have here!

**Comment by danhigham** [comment]
@danmarshall Actually, don't worry! All done :-)

**Comment by danmarshall** [comment]
Thanks! Published 1.2.1

**Comment by danhigham** [comment]
You're very welcome! I forgot to change the README to remove the item from the todo list!

**Comment by danmarshall** [comment]
Ok, fixed the readme! But I suppose they should just be issues ;) and not in the readme.

**Pull request merged**
